#ifndef INCLUDE_FS_DEFINES_H
#define INCLUDE_FS_DEFINES_H

#define FILE_FLAG_NONE 0x0
#define FILE_FLAG_READ 0x1
#define FILE_FLAG_WRITE 0x2
#define FILE_FLAG_RW (FILE_FLAG_READ | FILE_FLAG_WRITE)
#define FILE_FLAG_CREATE 0x4
#define FILE_FLAG_APPEND 0x8
#define FILE_CREATE_DIR 0x80

#define FILE_OP_FAILED -1
#define FILE_OP_SUCCESS 0
#define FILE_INVALID_FD -2
#define FILE_INVALID_TARGET -3
#define FILE_NO_CAPACITY -4
#define FILE_READ_OVER_END -5
#define FILE_INVALID_PERMISSIONS -6

#define TYPE_FILE 1
#define TYPE_DIR 2

#define FS_FILE_PERM_NONE 0x0
#define FS_FILE_PERM_READABLE 0x1
#define FS_FILE_PERM_WRITABLE 0x2
#define FS_FILE_PERM_EXECUTABLE 0x4

#endif